- name: Add CRIO Repo-1
  yum_repository:
    name: devel:kubic:libcontainers:stable
    description: Stable Releases of Upstream github.com/containers packages (CentOS_8)
    baseurl: https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/CentOS_8/
    gpgkey: https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/CentOS_8/repodata/repomd.xml.key
    gpgcheck: yes
    enabled: yes
- name: Add CRIO Repo-2
  yum_repository:
    name: devel:kubic:libcontainers:stable:cri-o:1.20
    description: devel:kubic:libcontainers:stable:cri-o:1.20 (CentOS_8)
    baseurl: https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.20/CentOS_8/
    gpgkey: https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.20/CentOS_8/repodata/repomd.xml.key
    gpgcheck: yes
    enabled: yes
- name: Install CRIO Runtime
  yum:
    name: cri-o
    state: present
